import { LegalLayout } from "@/components/LegalLayout";

export default function TermsAndSales() {
  return <LegalLayout kicker="Règles du service" title="CGU & CGV" intro="Ces conditions encadrent l'utilisation de l'application PICON et les commandes de tirages photo livrées au Togo. Elles complètent les informations affichées dans l'application au moment de la validation." sections={[
    { title: "Objet et acceptation", body: "Les présentes conditions régissent l'accès au site, à l'application PICON et aux services de tirage et de livraison. Le téléchargement de l'application ou la validation d'une commande vaut acceptation des conditions applicables au moment de l'utilisation." },
    { title: "Description du service", body: "PICON permet de charger des photos depuis une galerie mobile, de choisir un format et une quantité, de prévisualiser ou recadrer les images, de régler la commande puis de recevoir les tirages à l'adresse indiquée au Togo, selon les options disponibles." },
    { title: "Prix et paiement", body: "Les prix sont indiqués en francs CFA (XOF), toutes taxes comprises, hors frais éventuels de livraison affichés avant validation. Les moyens de paiement proposés sont Mixx by Yas/T-Money, Flooz/Moov Money et la carte bancaire. L'impression commence après confirmation et réception du paiement intégral." },
    { title: "Contenus chargés et propriété intellectuelle", body: "Vous devez détenir les droits nécessaires sur les photos transmises. Il est interdit de charger un contenu illégal, diffamatoire, violent, pornographique ou portant atteinte aux droits d'autrui. PICON peut refuser un fichier non conforme à ces règles." },
    { title: "Impression, délais et livraison", body: "Les délais indicatifs affichés sont de 72 heures pour le traitement standard et 24 heures pour l'option express, lorsque celle-ci est disponible. Une légère différence de teinte ou de cadrage peut apparaître entre l'écran et le papier. Les retards liés à une adresse incomplète, à l'absence du destinataire ou à un transporteur tiers ne sont pas imputables à PICON." },
    { title: "Réclamation, réimpression et remboursement", body: "En cas d'anomalie manifeste imputable à l'impression ou au conditionnement, contactez PICON dans les 48 heures suivant la réception avec des photos du problème. Après examen, PICON pourra proposer une réimpression ou un remboursement selon le cas. Les produits personnalisés ne peuvent pas être retournés pour un simple changement d'avis." },
    { title: "Évolution des conditions et contact", body: "PICON peut modifier ces conditions pour tenir compte de l'évolution du service ou de la réglementation. La version applicable est celle publiée lors de la commande. Pour toute question, écrivez à infos@photopicon.com ou appelez le +228 72 68 30 32 / 98 52 62 26." },
  ]} highlightTitle="Une question avant de commander ?" highlightBody="L'équipe PICON peut vous aider à choisir un format, comprendre un délai ou vérifier les options disponibles dans l'application." />;
}
