import { ArrowLeft, Mail, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { PiconLogo } from "./PiconLogo";
import { AmbientBackground } from "./AmbientBackground";

interface LegalSection { title: string; body: string; }
interface LegalLayoutProps { title: string; kicker: string; intro: string; sections: LegalSection[]; highlightTitle?: string; highlightBody?: string; }

export function LegalLayout({ title, kicker, intro, sections, highlightTitle, highlightBody }: LegalLayoutProps) {
  return <div className="min-h-screen bg-[#090a0c] text-white relative overflow-hidden"><AmbientBackground /><header className="relative z-10 border-b border-white/10 bg-[#090a0c]/80 backdrop-blur-md"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between gap-5"><Link href="/"><PiconLogo size="sm" withTagline={true} theme="dark" /></Link><Link href="/" className="inline-flex items-center gap-2 text-sm text-zinc-300 hover:text-white transition-colors"><ArrowLeft className="w-4 h-4" />Retour à l'accueil</Link></div></header><main className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24"><div className="max-w-3xl mb-12"><span className="inline-flex items-center gap-2 rounded-full border border-amber-400/20 bg-amber-400/10 px-3 py-1 text-xs font-mono uppercase tracking-widest text-amber-300"><ShieldCheck className="w-3.5 h-3.5" />{kicker}</span><h1 className="font-display text-4xl sm:text-6xl font-bold tracking-tight mt-5 mb-5">{title}</h1><p className="text-lg text-zinc-300 leading-relaxed">{intro}</p><p className="text-xs font-mono uppercase tracking-widest text-zinc-500 mt-6">Dernière mise à jour : 27 septembre 2026</p></div><div className="space-y-4">{sections.map((section, index) => <article key={section.title} className="rounded-2xl border border-white/10 bg-[#141519]/90 backdrop-blur-sm p-6 sm:p-8"><div className="flex gap-4"><span className="text-amber-400 font-mono text-sm pt-1">0{index + 1}</span><div><h2 className="text-xl sm:text-2xl font-bold text-white mb-3">{section.title}</h2><p className="text-sm sm:text-base text-zinc-300 leading-relaxed">{section.body}</p></div></div></article>)}</div>{highlightTitle && <div className="mt-8 rounded-2xl border border-amber-400/30 bg-gradient-to-br from-amber-400/15 to-transparent p-6 sm:p-8"><h2 className="text-xl sm:text-2xl font-bold text-white mb-3">{highlightTitle}</h2><p className="text-sm sm:text-base text-zinc-200 leading-relaxed">{highlightBody}</p><a href="mailto:infos@photopicon.com" className="inline-flex items-center gap-2 mt-5 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-black hover:bg-zinc-200 transition-colors"><Mail className="w-4 h-4" />infos@photopicon.com</a></div>}</main></div>;
}
