import { Frame, Check, Sparkles, Smartphone } from "lucide-react";
import { PlayStoreButton } from "./PlayStoreButton";

export function LivingRoomShowcase() {
  return (
    <section className="py-24 bg-[#0a0b0d] text-white border-t border-white/10 relative overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        <div className="lg:col-span-7 relative group rounded-3xl overflow-hidden shadow-2xl border border-white/10"><img src="/manus-storage/living_room_gallery_wall_919d5ee1.png" alt="Mur de cadres photo dans un salon moderne et chaleureux à Lomé" className="w-full h-[450px] sm:h-[550px] object-cover transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent flex flex-col justify-end p-6 sm:p-8"><span className="text-xs font-mono text-amber-400 uppercase tracking-widest mb-1">Inspiration Décoration & Mémoire</span><h3 className="text-xl sm:text-2xl font-bold text-white mb-2 font-display">Ce que vos photos peuvent devenir.</h3><p className="text-xs sm:text-sm text-zinc-300 max-w-lg">L'application commence dans votre galerie. L'histoire continue dans votre intérieur, avec des souvenirs que l'on peut réellement regarder et partager.</p></div></div>
        <div className="lg:col-span-5 space-y-6"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-amber-400 text-xs font-semibold tracking-wide uppercase"><Frame className="w-3.5 h-3.5" />De l'écran à la maison</div><h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight font-display text-white">PICON transforme un geste mobile en souvenir durable.</h2><p className="text-sm sm:text-base text-zinc-400 leading-relaxed">La vitrine vous inspire. L'application vous permet de parcourir les formats disponibles, préparer vos photos et retrouver l'ensemble de l'expérience PICON depuis votre smartphone.</p><div className="space-y-4 pt-2"><div className="flex items-start gap-3"><div className="w-6 h-6 rounded-full bg-amber-400/20 text-amber-400 flex items-center justify-center shrink-0 mt-0.5"><Check className="w-3.5 h-3.5" /></div><div><h4 className="text-sm font-bold text-white">Une expérience conçue autour de vos photos</h4><p className="text-xs text-zinc-400">Sélection, formats, cadrage et récapitulatif dans un même parcours.</p></div></div><div className="flex items-start gap-3"><div className="w-6 h-6 rounded-full bg-amber-400/20 text-amber-400 flex items-center justify-center shrink-0 mt-0.5"><Check className="w-3.5 h-3.5" /></div><div><h4 className="text-sm font-bold text-white">Une inspiration locale</h4><p className="text-xs text-zinc-400">Des souvenirs de Lomé et du Togo, pensés pour trouver leur place chez vous.</p></div></div><div className="flex items-start gap-3"><div className="w-6 h-6 rounded-full bg-amber-400/20 text-amber-400 flex items-center justify-center shrink-0 mt-0.5"><Check className="w-3.5 h-3.5" /></div><div><h4 className="text-sm font-bold text-white">Une application qui évolue avec vos usages</h4><p className="text-xs text-zinc-400">Retrouvez les options et promotions proposées par le laboratoire.</p></div></div></div><div className="pt-4"><PlayStoreButton label="Découvrir PICON sur Google Play" /></div></div>
      </div></div>
    </section>
  );
}
